/**
 * grocy REST API
 * Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](https://demo.grocy.info/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).
 *
 * The version of the OpenAPI document: 2.6.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import localVarRequest = require("request");
import http = require("http");

/* tslint:disable:no-unused-locals */
import { GenericErrorResponse } from "../model/genericErrorResponse";

import {
  ObjectSerializer,
  Authentication,
  VoidAuth,
  Interceptor
} from "../model/models";
import {
  HttpBasicAuth,
  HttpBearerAuth,
  ApiKeyAuth,
  OAuth
} from "../model/models";

import { HttpError, RequestFile } from "./apis";

let defaultBasePath = "http://grocy.lan/api";

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum FilesApiApiKeys {
  ApiKeyAuth
}

export class FilesApi {
  protected _basePath = defaultBasePath;
  protected _defaultHeaders: any = {};
  protected _useQuerystring: boolean = false;

  protected authentications = {
    default: <Authentication>new VoidAuth(),
    ApiKeyAuth: new ApiKeyAuth("header", "GROCY-API-KEY")
  };

  protected interceptors: Interceptor[] = [];

  constructor(basePath?: string);
  constructor(
    basePathOrUsername: string,
    password?: string,
    basePath?: string
  ) {
    if (password) {
      if (basePath) {
        this.basePath = basePath;
      }
    } else {
      if (basePathOrUsername) {
        this.basePath = basePathOrUsername;
      }
    }
  }

  set useQuerystring(value: boolean) {
    this._useQuerystring = value;
  }

  set basePath(basePath: string) {
    this._basePath = basePath;
  }

  set defaultHeaders(defaultHeaders: any) {
    this._defaultHeaders = defaultHeaders;
  }

  get defaultHeaders() {
    return this._defaultHeaders;
  }

  get basePath() {
    return this._basePath;
  }

  public setDefaultAuthentication(auth: Authentication) {
    this.authentications.default = auth;
  }

  public setApiKey(key: FilesApiApiKeys, value: string) {
    (this.authentications as any)[FilesApiApiKeys[key]].apiKey = value;
  }

  public addInterceptor(interceptor: Interceptor) {
    this.interceptors.push(interceptor);
  }

  /**
   *
   * @summary Deletes the given file
   * @param group The file group
   * @param fileName The file name (including extension)&lt;br&gt;**BASE64 encoded**
   */
  public async filesGroupFileNameDelete(
    group: string,
    fileName: string,
    options: { headers: { [name: string]: string } } = { headers: {} }
  ): Promise<{ response: http.IncomingMessage; body?: any }> {
    const localVarPath =
      this.basePath +
      "/files/{group}/{fileName}"
        .replace("{" + "group" + "}", encodeURIComponent(String(group)))
        .replace("{" + "fileName" + "}", encodeURIComponent(String(fileName)));
    let localVarQueryParameters: any = {};
    let localVarHeaderParams: any = (<any>Object).assign(
      {},
      this._defaultHeaders
    );
    const produces = ["application/json"];
    // give precedence to 'application/json'
    if (produces.indexOf("application/json") >= 0) {
      localVarHeaderParams.Accept = "application/json";
    } else {
      localVarHeaderParams.Accept = produces.join(",");
    }
    let localVarFormParams: any = {};

    // verify required parameter 'group' is not null or undefined
    if (group === null || group === undefined) {
      throw new Error(
        "Required parameter group was null or undefined when calling filesGroupFileNameDelete."
      );
    }

    // verify required parameter 'fileName' is not null or undefined
    if (fileName === null || fileName === undefined) {
      throw new Error(
        "Required parameter fileName was null or undefined when calling filesGroupFileNameDelete."
      );
    }

    (<any>Object).assign(localVarHeaderParams, options.headers);

    let localVarUseFormData = false;

    let localVarRequestOptions: localVarRequest.Options = {
      method: "DELETE",
      qs: localVarQueryParameters,
      headers: localVarHeaderParams,
      uri: localVarPath,
      useQuerystring: this._useQuerystring,
      json: true
    };

    let authenticationPromise = Promise.resolve();
    if (this.authentications.ApiKeyAuth.apiKey) {
      authenticationPromise = authenticationPromise.then(() =>
        this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions)
      );
    }
    authenticationPromise = authenticationPromise.then(() =>
      this.authentications.default.applyToRequest(localVarRequestOptions)
    );

    let interceptorPromise = authenticationPromise;
    for (const interceptor of this.interceptors) {
      interceptorPromise = interceptorPromise.then(() =>
        interceptor(localVarRequestOptions)
      );
    }

    return interceptorPromise.then(() => {
      if (Object.keys(localVarFormParams).length) {
        if (localVarUseFormData) {
          (<any>localVarRequestOptions).formData = localVarFormParams;
        } else {
          localVarRequestOptions.form = localVarFormParams;
        }
      }
      return new Promise<{ response: http.IncomingMessage; body?: any }>(
        (resolve, reject) => {
          localVarRequest(localVarRequestOptions, (error, response, body) => {
            if (error) {
              reject(error);
            } else {
              if (
                response.statusCode &&
                response.statusCode >= 200 &&
                response.statusCode <= 299
              ) {
                resolve({ response: response, body: body });
              } else {
                reject(new HttpError(response, body, response.statusCode));
              }
            }
          });
        }
      );
    });
  }
  /**
   * With proper Content-Type header
   * @summary Serves the given file
   * @param group The file group
   * @param fileName The file name (including extension)&lt;br&gt;**BASE64 encoded**
   * @param forceServeAs Force the file to be served as the given type
   * @param bestFitHeight Only when using &#x60;force_serve_as&#x60; &#x3D; &#x60;picture&#x60;: Downscale the picture to the given height while maintaining the aspect ratio
   * @param bestFitWidth Only when using &#x60;force_serve_as&#x60; &#x3D; &#x60;picture&#x60;: Downscale the picture to the given width while maintaining the aspect ratio
   */
  public async filesGroupFileNameGet(
    group: string,
    fileName: string,
    forceServeAs?: "picture",
    bestFitHeight?: number,
    bestFitWidth?: number,
    options: { headers: { [name: string]: string } } = { headers: {} }
  ): Promise<{ response: http.IncomingMessage; body: Buffer }> {
    const localVarPath =
      this.basePath +
      "/files/{group}/{fileName}"
        .replace("{" + "group" + "}", encodeURIComponent(String(group)))
        .replace("{" + "fileName" + "}", encodeURIComponent(String(fileName)));
    let localVarQueryParameters: any = {};
    let localVarHeaderParams: any = (<any>Object).assign(
      {},
      this._defaultHeaders
    );
    const produces = ["application/octet-stream", "application/json"];
    // give precedence to 'application/json'
    if (produces.indexOf("application/json") >= 0) {
      localVarHeaderParams.Accept = "application/json";
    } else {
      localVarHeaderParams.Accept = produces.join(",");
    }
    let localVarFormParams: any = {};

    // verify required parameter 'group' is not null or undefined
    if (group === null || group === undefined) {
      throw new Error(
        "Required parameter group was null or undefined when calling filesGroupFileNameGet."
      );
    }

    // verify required parameter 'fileName' is not null or undefined
    if (fileName === null || fileName === undefined) {
      throw new Error(
        "Required parameter fileName was null or undefined when calling filesGroupFileNameGet."
      );
    }

    if (forceServeAs !== undefined) {
      localVarQueryParameters["force_serve_as"] = ObjectSerializer.serialize(
        forceServeAs,
        "'picture'"
      );
    }

    if (bestFitHeight !== undefined) {
      localVarQueryParameters["best_fit_height"] = ObjectSerializer.serialize(
        bestFitHeight,
        "number"
      );
    }

    if (bestFitWidth !== undefined) {
      localVarQueryParameters["best_fit_width"] = ObjectSerializer.serialize(
        bestFitWidth,
        "number"
      );
    }

    (<any>Object).assign(localVarHeaderParams, options.headers);

    let localVarUseFormData = false;

    let localVarRequestOptions: localVarRequest.Options = {
      method: "GET",
      qs: localVarQueryParameters,
      headers: localVarHeaderParams,
      uri: localVarPath,
      useQuerystring: this._useQuerystring,
      encoding: null
    };

    let authenticationPromise = Promise.resolve();
    if (this.authentications.ApiKeyAuth.apiKey) {
      authenticationPromise = authenticationPromise.then(() =>
        this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions)
      );
    }
    authenticationPromise = authenticationPromise.then(() =>
      this.authentications.default.applyToRequest(localVarRequestOptions)
    );

    let interceptorPromise = authenticationPromise;
    for (const interceptor of this.interceptors) {
      interceptorPromise = interceptorPromise.then(() =>
        interceptor(localVarRequestOptions)
      );
    }

    return interceptorPromise.then(() => {
      if (Object.keys(localVarFormParams).length) {
        if (localVarUseFormData) {
          (<any>localVarRequestOptions).formData = localVarFormParams;
        } else {
          localVarRequestOptions.form = localVarFormParams;
        }
      }
      return new Promise<{ response: http.IncomingMessage; body: Buffer }>(
        (resolve, reject) => {
          localVarRequest(localVarRequestOptions, (error, response, body) => {
            if (error) {
              reject(error);
            } else {
              body = ObjectSerializer.deserialize(body, "Buffer");
              if (
                response.statusCode &&
                response.statusCode >= 200 &&
                response.statusCode <= 299
              ) {
                resolve({ response: response, body: body });
              } else {
                reject(new HttpError(response, body, response.statusCode));
              }
            }
          });
        }
      );
    });
  }
  /**
   * The file will be stored at /data/storage/{group}/{file_name} (you need to remember the group and file name to get or delete it again)
   * @summary Uploads a single file
   * @param group The file group
   * @param fileName The file name (including extension)&lt;br&gt;**BASE64 encoded**
   * @param body
   */
  public async filesGroupFileNamePut(
    group: string,
    fileName: string,
    body?: RequestFile,
    options: { headers: { [name: string]: string } } = { headers: {} }
  ): Promise<{ response: http.IncomingMessage; body?: any }> {
    const localVarPath =
      this.basePath +
      "/files/{group}/{fileName}"
        .replace("{" + "group" + "}", encodeURIComponent(String(group)))
        .replace("{" + "fileName" + "}", encodeURIComponent(String(fileName)));
    let localVarQueryParameters: any = {};
    let localVarHeaderParams: any = (<any>Object).assign(
      {},
      this._defaultHeaders
    );
    const produces = ["application/json"];
    // give precedence to 'application/json'
    if (produces.indexOf("application/json") >= 0) {
      localVarHeaderParams.Accept = "application/json";
    } else {
      localVarHeaderParams.Accept = produces.join(",");
    }
    let localVarFormParams: any = {};

    // verify required parameter 'group' is not null or undefined
    if (group === null || group === undefined) {
      throw new Error(
        "Required parameter group was null or undefined when calling filesGroupFileNamePut."
      );
    }

    // verify required parameter 'fileName' is not null or undefined
    if (fileName === null || fileName === undefined) {
      throw new Error(
        "Required parameter fileName was null or undefined when calling filesGroupFileNamePut."
      );
    }

    (<any>Object).assign(localVarHeaderParams, options.headers);

    let localVarUseFormData = false;

    let localVarRequestOptions: localVarRequest.Options = {
      method: "PUT",
      qs: localVarQueryParameters,
      headers: localVarHeaderParams,
      uri: localVarPath,
      useQuerystring: this._useQuerystring,
      json: true,
      body: ObjectSerializer.serialize(body, "RequestFile")
    };

    let authenticationPromise = Promise.resolve();
    if (this.authentications.ApiKeyAuth.apiKey) {
      authenticationPromise = authenticationPromise.then(() =>
        this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions)
      );
    }
    authenticationPromise = authenticationPromise.then(() =>
      this.authentications.default.applyToRequest(localVarRequestOptions)
    );

    let interceptorPromise = authenticationPromise;
    for (const interceptor of this.interceptors) {
      interceptorPromise = interceptorPromise.then(() =>
        interceptor(localVarRequestOptions)
      );
    }

    return interceptorPromise.then(() => {
      if (Object.keys(localVarFormParams).length) {
        if (localVarUseFormData) {
          (<any>localVarRequestOptions).formData = localVarFormParams;
        } else {
          localVarRequestOptions.form = localVarFormParams;
        }
      }
      return new Promise<{ response: http.IncomingMessage; body?: any }>(
        (resolve, reject) => {
          localVarRequest(localVarRequestOptions, (error, response, body) => {
            if (error) {
              reject(error);
            } else {
              if (
                response.statusCode &&
                response.statusCode >= 200 &&
                response.statusCode <= 299
              ) {
                resolve({ response: response, body: body });
              } else {
                reject(new HttpError(response, body, response.statusCode));
              }
            }
          });
        }
      );
    });
  }
}
