/**
 * grocy REST API
 * Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](https://demo.grocy.info/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).
 *
 * The version of the OpenAPI document: 2.6.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";

export enum ExposedEntityButNoListing {
  Products = <any>"products",
  Chores = <any>"chores",
  Batteries = <any>"batteries",
  Locations = <any>"locations",
  QuantityUnits = <any>"quantity_units",
  QuantityUnitConversions = <any>"quantity_unit_conversions",
  ShoppingList = <any>"shopping_list",
  ShoppingLists = <any>"shopping_lists",
  Recipes = <any>"recipes",
  RecipesPos = <any>"recipes_pos",
  RecipesNestings = <any>"recipes_nestings",
  Tasks = <any>"tasks",
  TaskCategories = <any>"task_categories",
  ProductGroups = <any>"product_groups",
  Equipment = <any>"equipment",
  Userfields = <any>"userfields",
  Userentities = <any>"userentities",
  Userobjects = <any>"userobjects",
  MealPlan = <any>"meal_plan"
}
