/**
 * grocy REST API
 * Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](https://demo.grocy.info/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).
 *
 * The version of the OpenAPI document: 2.6.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";

export class InlineObject3 {
  /**
   * The amount to transfer - please note that when tare weight handling for the product is enabled, this needs to be the amount including the container weight (gross), the amount to be posted will be automatically calculated based on what is in stock and the defined tare weight
   */
  "amount"?: number;
  /**
   * A valid location id, the location from where the product should be transfered
   */
  "locationIdFrom"?: number;
  /**
   * A valid location id, the location to where the product should be transfered
   */
  "locationIdTo"?: number;
  /**
   * A specific stock entry id to transfer, if used, the amount has to be 1
   */
  "stockEntryId"?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "amount",
      baseName: "amount",
      type: "number"
    },
    {
      name: "locationIdFrom",
      baseName: "location_id_from",
      type: "number"
    },
    {
      name: "locationIdTo",
      baseName: "location_id_to",
      type: "number"
    },
    {
      name: "stockEntryId",
      baseName: "stock_entry_id",
      type: "string"
    }
  ];

  static getAttributeTypeMap() {
    return InlineObject3.attributeTypeMap;
  }
}
