/**
 * grocy REST API
 * Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](https://demo.grocy.info/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).
 *
 * The version of the OpenAPI document: 2.6.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";
import { InlineResponse200GrocyVersion } from "./inlineResponse200GrocyVersion";

export class InlineResponse200 {
  "grocyVersion"?: InlineResponse200GrocyVersion;
  "phpVersion"?: string;
  "sqliteVersion"?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "grocyVersion",
      baseName: "grocy_version",
      type: "InlineResponse200GrocyVersion"
    },
    {
      name: "phpVersion",
      baseName: "php_version",
      type: "string"
    },
    {
      name: "sqliteVersion",
      baseName: "sqlite_version",
      type: "string"
    }
  ];

  static getAttributeTypeMap() {
    return InlineResponse200.attributeTypeMap;
  }
}
