/**
 * grocy REST API
 * Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](https://demo.grocy.info/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).
 *
 * The version of the OpenAPI document: 2.6.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";

export class InlineObject13 {
  /**
   * A valid product id of the item on the shopping list
   */
  "productId"?: number;
  /**
   * A valid shopping list id, when omitted, the default shopping list (with id 1) is used
   */
  "listId"?: number;
  /**
   * The amount of product units to add, when omitted, the default amount of 1 is used
   */
  "productAmount"?: number;
  /**
   * The note of the shopping list item
   */
  "note"?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "productId",
      baseName: "product_id",
      type: "number"
    },
    {
      name: "listId",
      baseName: "list_id",
      type: "number"
    },
    {
      name: "productAmount",
      baseName: "product_amount",
      type: "number"
    },
    {
      name: "note",
      baseName: "note",
      type: "string"
    }
  ];

  static getAttributeTypeMap() {
    return InlineObject13.attributeTypeMap;
  }
}
