/**
 * grocy REST API
 * Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](https://demo.grocy.info/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).
 *
 * The version of the OpenAPI document: 2.6.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";

export class InlineObject16 {
  /**
   * The time of when the chore was executed, when omitted, the current time is used
   */
  "trackedTime"?: Date;
  /**
   * A valid user id of who executed this chore, when omitted, the currently authenticated user will be used
   */
  "doneBy"?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "trackedTime",
      baseName: "tracked_time",
      type: "Date"
    },
    {
      name: "doneBy",
      baseName: "done_by",
      type: "number"
    }
  ];

  static getAttributeTypeMap() {
    return InlineObject16.attributeTypeMap;
  }
}
