/**
 * grocy REST API
 * Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](https://demo.grocy.info/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).
 *
 * The version of the OpenAPI document: 2.6.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";

export class StockLocation {
  "id"?: number;
  "productId"?: number;
  "locationId"?: number;
  "locationName"?: string;
  "locationIsFreezer"?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "number"
    },
    {
      name: "productId",
      baseName: "product_id",
      type: "number"
    },
    {
      name: "locationId",
      baseName: "location_id",
      type: "number"
    },
    {
      name: "locationName",
      baseName: "location_name",
      type: "string"
    },
    {
      name: "locationIsFreezer",
      baseName: "location_is_freezer",
      type: "number"
    }
  ];

  static getAttributeTypeMap() {
    return StockLocation.attributeTypeMap;
  }
}
