/**
 * grocy REST API
 * Authentication is done via API keys (header *GROCY-API-KEY* or same named query parameter), which you can manage [here](https://demo.grocy.info/manageapikeys).<br>Additionally requests from within the frontend are also valid (via session cookie).
 *
 * The version of the OpenAPI document: 2.6.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";
import { StockTransactionType } from "./stockTransactionType";

export class StockLogEntry {
  "id"?: number;
  "productId"?: number;
  "amount"?: number;
  "bestBeforeDate"?: string;
  "purchasedDate"?: Date;
  "usedDate"?: Date;
  "spoiled"?: boolean;
  "stockId"?: string;
  "transactionType"?: StockTransactionType;
  "rowCreatedTimestamp"?: Date;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "number"
    },
    {
      name: "productId",
      baseName: "product_id",
      type: "number"
    },
    {
      name: "amount",
      baseName: "amount",
      type: "number"
    },
    {
      name: "bestBeforeDate",
      baseName: "best_before_date",
      type: "string"
    },
    {
      name: "purchasedDate",
      baseName: "purchased_date",
      type: "Date"
    },
    {
      name: "usedDate",
      baseName: "used_date",
      type: "Date"
    },
    {
      name: "spoiled",
      baseName: "spoiled",
      type: "boolean"
    },
    {
      name: "stockId",
      baseName: "stock_id",
      type: "string"
    },
    {
      name: "transactionType",
      baseName: "transaction_type",
      type: "StockTransactionType"
    },
    {
      name: "rowCreatedTimestamp",
      baseName: "row_created_timestamp",
      type: "Date"
    }
  ];

  static getAttributeTypeMap() {
    return StockLogEntry.attributeTypeMap;
  }
}
